### ISSUE TITLE
FreeBSD 13 test fail: mmap invalid argument

### ISSUE THREAD

**Issue by gdiazlo** [koka-lang/libmprompt#4]
Hello

The test are failing on FreeBSD13 (seems they introduced PROT_MAX on this version), with a EINVAL error in mmap call when compiling a release version.

```
% ./test_mp_async 
run requests...
libmprompt: error: failed to allocate mmap memory of size 274877906944
            code : 22: Invalid argument
libmprompt: error: unable to allocate a stack
4000: signal: sys: abort (core dumped)
% 
```

Removing `PROT_MAX` but leaving `prot |= PROT_READ | PROT_WRITE` the test does not crash, but never ends, eating a single core for more than an hour, with no increase of memory usage. The other tests behave simmilarly.

**Comment by daanx** [comment]
Ouch -- thanks for the report; I will try to repro this on my VM

**Comment by daanx** [comment]
Fixed in the latest `dev`; thanks

**Comment by gdiazlo** [comment]
Thanks a lot! I'll try it. mmap is such a complex beast :)
